# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - id: create_token
      uses: tibdex/github-app-token@v2
      with:
        # use the private key and app id secret that we created in the Github App section
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - name: Reconfigure git to use HTTP authentication
        # Fix our git override using the generated token from the create_token step + use the "x-access-token".
      run: |
        git config --global url."https://x-access-token:${{ steps.create_token.outputs.token }}@github.com".insteadOf ssh://git@github.com
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - run: npm run lint
    - run: npm test

